export default class Business {
    public logo: string = "";
    public name: string = "";
    public showNameAsText: boolean = false;
    public address1: string = "";
    public address2: string = "";
    public city: string = "";
    public country: string = "";
    public zip: string = "";
    public email: string = "";
    public tel: string = "";
    public invoicenumber: number = 1;
    public addtax: boolean = false;
    public taxname: string = "";
    public taxpercentage: number = 0;
    public bankdetails: string = "";
    public countrycode: string = "";
    public currencysymbol: string = "$";
}
