---
- name: Git - Push changes to repo
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: add new files
      command: git add -A
      args:
        chdir: /home/cornel/src/vueblocks/invoice-demo/front-end-deploy
    - name: git commit
      command: git commit -m "latest changes"      
      args:
        chdir: /home/cornel/src/vueblocks/invoice-demo/front-end-deploy
    - name: run git command
      command: git push -u origin master
      args:
        chdir: /home/cornel/src/vueblocks/invoice-demo/front-end-deploy
